hdmifish/petal

petal/commands.py, petal/mcname.py
- Fixed `!wlme` input bug from yesterday
- Bot will send a DM to users to let them know they got approved
- Queries/reports should no longer ping people in them
- Database entries can be selectively suspended from the whitelist
- Etc.
- Removed spaghetti
=> Local Database Restructuring + Optimizations

petal/commands.py, petal/mcname.py
Use of `!wlsuspend`:
`!wlsuspend <profile_identifier> [<term_y/n>]`
```python
wordPos = ["true", "on", "yes", "active", "1", "enable"]
wordNeg = ["false", "off", "no", "inactive", "0", "disable"]
```
*examples:*
`!wlsuspend davarice`
`!wlsuspend 106605138893889536 on`
`!wlsuspend 91466c33-ae7d-4beb-9e26-944b0614b167 disable`
=> Various fixes and improvements

petal/commands.py, petal/mcname.py
`!wlquery pending`: List all pending entries
`!wlquery (restricted|suspended)`: List all suspended entries
`!wlquery <identifier>`: No change
=> Misc additional functionality

petal/commands.py, petal/mcname.py
Also some other stuff that might break but hopefully wont
=> !WLGone fix...finally

_exampleconfig.yml, petal/commands.py, petal/mcname.py, petal/mcutil.py
Significant improvements in aspects I have learned more about since initially implementing them
Significant:
- `!WL*` docstrings expanded and corrected
- Event logging improved and expanded
- Shift of MC module from a group of functions to a small set of classes
- MC module now accesses bot config
=> Application of new learnings

README.md, _exampleconfig.yml, petal/commands.py, petal/mcutil.py
I added the replacement but forgot to actually remove the old one...derp
=> ACTUALLY replaced unreliable badge

_exampleconfig.yml, petal/mcutil.py
This will require another small config change
=> Added Operator list to match Whitelist file filling

_exampleconfig.yml, petal/commands.py, petal/mcutil.py
=> Experimental push for testing in production

petal/commands.py
Includes removal of all channel restrictions in favor of Minecraft operator level restrictions
=> Full implementation of WLAuthenticate

petal/commands.py, petal/mcutil.py
Includes indicator as to whether user is in the server
=> WLQuery adjustment

README.md, petal/__init__.py, petal/commands.py, petal/config.py, petal/dbhandler.py, petal/grasslands.py, petal/petal.py, requirements.txt, run.py
Formatting improvements, and half of an LFG command set; Only implemented List and Set functionalities for now, requires thorough testing before moving on to the function that might ping people
=> Testing In Production

petal/commands.py, petal/dbhandler.py, petal/mcutil.py
Commands to search the DB for people who want to play a game, and to fully delete your own LFG entries
=> LFG Find and Clear

petal/commands.py
Codes can be assigned, and an automatically generated help function is now available
Additionally: all !WL* commands now check for the correct config options, rather than checking for one twice
=> Further progress on Suspension Codes

petal/commands.py, petal/petal.py
Resolved Buggered tickets 13, 19, 23, 30, 33
=> Five Fixes

_exampleconfig.yml, petal/commands.py, petal/petal.py
=> QoL Chapter 1: The Aged Skeletons

petal/commands.py, petal/mcutil.py
Improvements to documentation and maintenance of whitelist interface DB
=> QoL Chapter 2: "Take Note"

petal/commands.py, petal/mcutil.py
Who needs return data? Oh yeah I do.
=> Non-useless output for WLNote()

petal/commands.py
=> Foolishness fixed

petal/commands.py
Rather than accepting the profile ID given, I had made the function extract the Discord ID from the profile, and use that...which would only return the first profile under the Discord ID.
=> Fool of a Took

_exampleconfig.yml, petal/petal.py
~~TODO: Generalize into an autoreply system using config~~
=> pokemon go away pls

petal/commands/__init__.py, petal/commands/admin.py, petal/commands/core.py, petal/commands/custom.py, petal/commands/dev.py, petal/commands/minecraft/auth.py, petal/commands/public.py, petal/commands/util.py, petal/mcutil.py
Fix for minor issues not caught/considered until post-merge
=> Small hotfixes

petal/commands/__init__.py, petal/commands/core.py
=> Fix mistake preventing correct recognition of cross-server roles

petal/commands/__init__.py, petal/commands/admin.py, petal/commands/core.py, petal/commands/custom.py, petal/commands/dev.py, petal/commands/listener.py, petal/commands/minecraft/mc_mod.py, petal/commands/public.py, petal/commands/social.py, petal/commands/util.py
AskPatch and PAForce admin-restricted pending full integration.
Current implementation is essentially just a port, but accepting this PR now will restore functionality.
=> Reimplementation of various auxiliary tools

petal/commands/__init__.py, petal/commands/admin.py, petal/commands/dev.py, petal/commands/event.py, petal/commands/manager.py, petal/commands/social.py, petal/commands/sudo.py, petal/commands/template.py, petal/menu.py, petal/util/grammar.py
- Add three developer-level test commands for the reaction menus
- Add reaction menus in the !event and !update commands
- Add whitelisted !sudo command to give access to commands of any other auth module
=> Implement Reaction-based UI for multiple choice selections

petal/changelog.txt, petal/commands/__init__.py, petal/commands/dev.py, petal/commands/event.py, petal/commands/listener.py, petal/commands/minecraft/mc_mod.py, petal/commands/minecraft/mc_public.py, petal/commands/public.py, petal/commands/social.py, petal/commands/util.py, petal/grasslands.py, petal/petal.py, post-merge.sample, requirements.txt, version_info.sh
```
[v0.7.0] (2018-04-04)
First changelog be gentle; Biiiiiiiiig updates since then
Since the last documented update:
+- Ripped out and replaced the whole single-module commands system with a package-based "router" system with modular authentication and a rather crude (but working!) approximation of C-style option flags
+ New commands; Main ones: argtest, calias, define, info, roll, sudo, time
* Overhauled commands: commands, help, new, wiki, xkcd
+ Reaction-based UI menus for choices n stuff
+ Implemented basic type checking for --options
* Various spelling fixes, removal of many line-end whitespaces
```
=> Version 0.7.0

petal/changelog.txt, petal/commands/__init__.py, petal/commands/core.py, version_info.sh
=> 0.9.1 (Hotfix)

.gitignore, petal/__init__.py, petal/commands/core.py, petal/commands/public.py, version_info.sh
Various buggos and slows murdered.
=> v1.0.0b3 Hotfix

petal/__init__.py, petal/changelog.txt, petal/checks.py, petal/commands/core.py, petal/commands/mod.py, petal/types.py, petal/util/embeds.py, version_info.sh
Fixes Muting issue, standardizes Join/Part
=> v1.0.0b4 Hotfix

petal/__init__.py, petal/util/cdn.py, petal/util/embeds.py
=> Hotfix to the Hotfix

petal/changelog.txt, petal/commands/dev.py, petal/commands/manager.py, petal/commands/minecraft/mc_mod.py, petal/commands/minecraft/mc_public.py, petal/commands/mod.py, petal/commands/social.py, petal/dbhandler.py, petal/menu.py, petal/util/grammar.py, version_info.sh
Should fix the problems with the Whitelisting commands.
=> v1.0.0b6 Hotfix

petal/__init__.py, petal/changelog.txt, petal/commands/__init__.py, petal/commands/core.py, petal/commands/util.py, version_info.sh
Fixes issue with silent Auth Failure.
=> Version 1.0.0: Release Candidate 1

petal/changelog.txt, petal/commands/__init__.py, petal/commands/dev.py, petal/commands/util.py, petal/util/bits.py, version_info.sh
=> Version 1.0.0: Release Candidate 2

petal/commands/public.py
Figured we could show our support
=> added teamtrees.org command

_exampleconfig.yml, petal/__init__.py, petal/etc.py
Takes members count data from bot and exports that into google spreadsheet, giving us awesome stats about how many members we have and are gaining or losing, horray!
=> Stats To Spreadsheets, Yay!

petal/dbhandler.py, petal/grasslands.py
=> Fixed dbhandler cluttering logs and added flag to logging.

petal/__init__.py, petal/changelog.txt, petal/checks.py, petal/commands/dev.py, petal/commands/event.py, petal/commands/manager.py, petal/commands/minecraft/mc_mod.py, petal/commands/mod.py, petal/commands/public.py, petal/commands/util.py, petal/menu.py, petal/util/fmt.py, petal/util/minecraft.py, petal/util/questions.py, version_info.sh
+ Questions Module for extremely easy interactivity
* Numerous corrections
=> Version 1.0.0: Release Candidate 5

_exampleconfig.yml, petal/changelog.txt, petal/commands/public.py, version_info.sh
=> Version 1.1.0 - Scholar of the First STDIN

petal/__init__.py, petal/changelog.txt, petal/commands/__init__.py, petal/commands/core.py, petal/commands/dev.py, petal/commands/event.py, petal/commands/listener.py, petal/commands/minecraft/mc_mod.py, petal/commands/mod.py, petal/commands/public.py, petal/commands/util.py, petal/dbhandler.py, petal/social_integration.py, requirements.txt
Added LazyMath (Unit Conversions)
Added LazyMoney (Exchange Rates + Crypto)
Spooky Clock and Santa Clock are now year-aware
Fixed DBHandler not properly creating new users. Should reduce log spam
=> Added LazyMoney and LazyMath features.

petal/commands/public.py, petal/dbhandler.py, requirements.txt
See above, just had some compat issues
=> Updated libraries
